In [1]:
import torch

ModuleNotFoundError: ignored

In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
import torch

**Hence pytorch is successfully installed** 

Let us model a simple single node neural network 

In [0]:
def activation_function(x):
  return 1/(1+torch.exp(-x))

Let us start

In [8]:
torch.manual_seed(7)

In [0]:
features=torch.randn(1,5)

In [12]:
features

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [0]:
weights=torch.randn_like(features)

In [14]:
weights

tensor([[0.3177, 0.1328, 0.1373, 0.2405, 1.3955]])

In [0]:
bias=torch.randn(1,1)

In [16]:
bias

tensor([[1.3470]])

Simple Execution

In [0]:
y=activation_function(torch.sum(weights*features)+bias)

In [18]:
y

tensor([[0.2443]])