In [0]:
import torch

In [0]:
def activation_function(x):
  return 1/(1+torch.exp(-x))

In [0]:
torch.manual_seed(7)
features=torch.randn(1,5)
weights=torch.randn_like(features)
bias=torch.randn(1,1)

In [0]:
y=activation_function(torch.mm(features,weights.view(5,1))+bias)

In [6]:
y

tensor([[0.1595]])

 **Lets do a multi layer neural network**

In [32]:
torch.manual_seed(7)
features=torch.randn((1,3))
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [31]:
input1=features.shape[1]
hidden=2
output=1
print(input1)

3


In [34]:
weight1=torch.randn(input1,hidden)
weight2=torch.randn(hidden,output)
print(weight1)
print(weight2)

tensor([[0.1328, 0.1373],
        [0.2405, 1.3955],
        [1.3470, 2.4382]])
tensor([[0.2028],
        [2.4505]])


In [35]:
bias1=torch.randn(1,hidden)
bias2=torch.randn(1,output)
print(bias1)
print(bias2)

tensor([[2.0256, 1.7792]])
tensor([[-0.9179]])


In [36]:
h=activation_function(torch.mm(features,weight1)+bias1)
h

tensor([[0.9698, 0.9943]])

In [27]:
weight2

tensor([[ 1.2799],
        [-0.9941]])

In [0]:
output=activation_function(torch.mm(h,weight2)+bias2)

In [29]:
output

tensor([[0.9370]])

Thats it :-)